website-backend/src/Entity/ResearchPermits.php
<?php

namespace App\Entity;

use App\Repository\ResearchPermitsRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=ResearchPermitsRepository::class)
 * @ApiResource(
 *   normalizationContext={"groups"={"research-permits:read"}},
 *   denormalizationContext={"groups"={"research-permits:write"}}
 * )
 */
class ResearchPermits
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"research-permits:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"research-permits:read", "research-permits:write"})
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"research-permits:read", "research-permits:write"})
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     * @Groups({"research-permits:read", "research-permits:write"})
     */
    private $file_type;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * @Groups({"research-permits:read", "research-permits:write"})
     */
    private $size;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"research-permits:read", "research-permits:write"})
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFileType(): ?string
    {
        return $this->file_type;
    }

    public function setFileType(?string $file_type): self
    {
        $this->file_type = $file_type;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(?string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

website-backend/src/Form/ResearchPermitsType.php
<?php

namespace App\Form;

use App\Entity\ResearchPermits;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResearchPermitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('file_type')
            ->add('size')
            ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ResearchPermits::class,
        ]);
    }
}

website-backend/src/Controller/ResearchPermitsController.php
<?php

namespace App\Controller;

use App\Entity\ResearchPermits;
use App\Form\ResearchPermits1Type;
use App\Repository\ResearchPermitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/research/permits")
 */
class ResearchPermitsController extends AbstractController
{
    /**
     * @Route("/", name="app_research_permits_index", methods={"GET"})
     */
    public function index(ResearchPermitsRepository $researchPermitsRepository): Response
    {
        return $this->render('research_permits/index.html.twig', [
            'research_permits' => $researchPermitsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_research_permits_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ResearchPermitsRepository $researchPermitsRepository): Response
    {
        $researchPermit = new ResearchPermits();
        $form = $this->createForm(ResearchPermits1Type::class, $researchPermit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $researchPermitsRepository->add($researchPermit, true);

            return $this->redirectToRoute('app_research_permits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('research_permits/new.html.twig', [
            'research_permit' => $researchPermit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_research_permits_show", methods={"GET"})
     */
    public function show(ResearchPermits $researchPermit): Response
    {
        return $this->render('research_permits/show.html.twig', [
            'research_permit' => $researchPermit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_research_permits_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ResearchPermits $researchPermit, ResearchPermitsRepository $researchPermitsRepository): Response
    {
        $form = $this->createForm(ResearchPermits1Type::class, $researchPermit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $researchPermitsRepository->add($researchPermit, true);

            return $this->redirectToRoute('app_research_permits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('research_permits/edit.html.twig', [
            'research_permit' => $researchPermit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_research_permits_delete", methods={"POST"})
     */
    public function delete(Request $request, ResearchPermits $researchPermit, ResearchPermitsRepository $researchPermitsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$researchPermit->getId(), $request->request->get('_token'))) {
            $researchPermitsRepository->remove($researchPermit, true);
        }

        return $this->redirectToRoute('app_research_permits_index', [], Response::HTTP_SEE_OTHER);
    }
}

website-backend/templates/research_permits/_delete_form.html.twig
<form method="post" action="{{ path('app_research_permits_delete', {'id': research_permit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ research_permit.id) }}">
    <button class="btn">Delete</button>
</form>

website-backend/templates/research_permits/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

website-backend/templates/research_permits/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ResearchPermits{% endblock %}

{% block body %}
    <h1>Edit ResearchPermits</h1>

    {{ include('research_permits/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_research_permits_index') }}">back to list</a>

    {{ include('research_permits/_delete_form.html.twig') }}
{% endblock %}

website-backend/templates/research_permits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ResearchPermits index{% endblock %}

{% block body %}
    <h1>ResearchPermits index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>File_type</th>
                <th>Size</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for research_permit in research_permits %}
            <tr>
                <td>{{ research_permit.id }}</td>
                <td>{{ research_permit.title }}</td>
                <td>{{ research_permit.description }}</td>
                <td>{{ research_permit.fileType }}</td>
                <td>{{ research_permit.size }}</td>
                <td>{{ research_permit.createdAt ? research_permit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_research_permits_show', {'id': research_permit.id}) }}">show</a>
                    <a href="{{ path('app_research_permits_edit', {'id': research_permit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_research_permits_new') }}">Create new</a>
{% endblock %}

website-backend/templates/research_permits/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ResearchPermits{% endblock %}

{% block body %}
    <h1>Create new ResearchPermits</h1>

    {{ include('research_permits/_form.html.twig') }}

    <a href="{{ path('app_research_permits_index') }}">back to list</a>
{% endblock %}

website-backend/templates/research_permits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ResearchPermits{% endblock %}

{% block body %}
    <h1>ResearchPermits</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ research_permit.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ research_permit.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ research_permit.description }}</td>
            </tr>
            <tr>
                <th>File_type</th>
                <td>{{ research_permit.fileType }}</td>
            </tr>
            <tr>
                <th>Size</th>
                <td>{{ research_permit.size }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ research_permit.createdAt ? research_permit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_research_permits_index') }}">back to list</a>

    <a href="{{ path('app_research_permits_edit', {'id': research_permit.id}) }}">edit</a>

    {{ include('research_permits/_delete_form.html.twig') }}
{% endblock %}