website-backend/src/Entity/ProcurementDocuments.php
<?php

namespace App\Entity;

use App\Repository\ProcurementDocumentsRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ProcurementDocumentsRepository::class)
 * @ApiResource(
 *   normalizationContext={"groups"={"procurement-documents:read"}},
 *   denormalizationContext={"groups"={"procurement-documents:write"}}
 * )
 */
class ProcurementDocuments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"procurement-documents:read"})
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=ProcurementBids::class, inversedBy="procurement_documents")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"procurement-documents:read", "procurement-documents:write"})
     */
    private $procurement_bids;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Groups({"procurement-documents:read", "procurement-documents:write"})
     */
    private $document_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProcurementBids(): ?ProcurementBids
    {
        return $this->procurement_bids;
    }

    public function setProcurementBids(?ProcurementBids $procurement_bids): self
    {
        $this->procurement_bids = $procurement_bids;

        return $this;
    }

    public function getDocumentName(): ?string
    {
        return $this->document_name;
    }

    public function setDocumentName(?string $document_name): self
    {
        $this->document_name = $document_name;

        return $this;
    }
}

website-backend/src/Form/ProcurementDocumentsType.php
<?php

namespace App\Form;

use App\Entity\ProcurementDocuments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProcurementDocumentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('document_name')
            ->add('procurement_bids')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProcurementDocuments::class,
        ]);
    }
}

website-backend/src/Controller/ProcurementDocumentsController.php
<?php

namespace App\Controller;

use App\Entity\ProcurementDocuments;
use App\Form\ProcurementDocuments1Type;
use App\Repository\ProcurementDocumentsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/procurement/documents")
 */
class ProcurementDocumentsController extends AbstractController
{
    /**
     * @Route("/", name="app_procurement_documents_index", methods={"GET"})
     */
    public function index(ProcurementDocumentsRepository $procurementDocumentsRepository): Response
    {
        return $this->render('procurement_documents/index.html.twig', [
            'procurement_documents' => $procurementDocumentsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_procurement_documents_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProcurementDocumentsRepository $procurementDocumentsRepository): Response
    {
        $procurementDocument = new ProcurementDocuments();
        $form = $this->createForm(ProcurementDocuments1Type::class, $procurementDocument);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $procurementDocumentsRepository->add($procurementDocument, true);

            return $this->redirectToRoute('app_procurement_documents_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('procurement_documents/new.html.twig', [
            'procurement_document' => $procurementDocument,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_procurement_documents_show", methods={"GET"})
     */
    public function show(ProcurementDocuments $procurementDocument): Response
    {
        return $this->render('procurement_documents/show.html.twig', [
            'procurement_document' => $procurementDocument,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_procurement_documents_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ProcurementDocuments $procurementDocument, ProcurementDocumentsRepository $procurementDocumentsRepository): Response
    {
        $form = $this->createForm(ProcurementDocuments1Type::class, $procurementDocument);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $procurementDocumentsRepository->add($procurementDocument, true);

            return $this->redirectToRoute('app_procurement_documents_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('procurement_documents/edit.html.twig', [
            'procurement_document' => $procurementDocument,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_procurement_documents_delete", methods={"POST"})
     */
    public function delete(Request $request, ProcurementDocuments $procurementDocument, ProcurementDocumentsRepository $procurementDocumentsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$procurementDocument->getId(), $request->request->get('_token'))) {
            $procurementDocumentsRepository->remove($procurementDocument, true);
        }

        return $this->redirectToRoute('app_procurement_documents_index', [], Response::HTTP_SEE_OTHER);
    }
}

website-backend/templates/procurement_documents/_delete_form.html.twig
<form method="post" action="{{ path('app_procurement_documents_delete', {'id': procurement_document.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ procurement_document.id) }}">
    <button class="btn">Delete</button>
</form>

website-backend/templates/procurement_documents/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

website-backend/templates/procurement_documents/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProcurementDocuments{% endblock %}

{% block body %}
    <h1>Edit ProcurementDocuments</h1>

    {{ include('procurement_documents/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_procurement_documents_index') }}">back to list</a>

    {{ include('procurement_documents/_delete_form.html.twig') }}
{% endblock %}

website-backend/templates/procurement_documents/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProcurementDocuments index{% endblock %}

{% block body %}
    <h1>ProcurementDocuments index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Document_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for procurement_document in procurement_documents %}
            <tr>
                <td>{{ procurement_document.id }}</td>
                <td>{{ procurement_document.documentName }}</td>
                <td>
                    <a href="{{ path('app_procurement_documents_show', {'id': procurement_document.id}) }}">show</a>
                    <a href="{{ path('app_procurement_documents_edit', {'id': procurement_document.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_procurement_documents_new') }}">Create new</a>
{% endblock %}

website-backend/templates/procurement_documents/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProcurementDocuments{% endblock %}

{% block body %}
    <h1>Create new ProcurementDocuments</h1>

    {{ include('procurement_documents/_form.html.twig') }}

    <a href="{{ path('app_procurement_documents_index') }}">back to list</a>
{% endblock %}

website-backend/templates/procurement_documents/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProcurementDocuments{% endblock %}

{% block body %}
    <h1>ProcurementDocuments</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ procurement_document.id }}</td>
            </tr>
            <tr>
                <th>Document_name</th>
                <td>{{ procurement_document.documentName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_procurement_documents_index') }}">back to list</a>

    <a href="{{ path('app_procurement_documents_edit', {'id': procurement_document.id}) }}">edit</a>

    {{ include('procurement_documents/_delete_form.html.twig') }}
{% endblock %}