website-backend/src/Entity/Vacancies.php
<?php

namespace App\Entity;

use App\Repository\VacanciesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=VacanciesRepository::class)
 *@ApiResource(
 *  normalizationContext={"groups"={"vacancies:read"}},
 *  denormalizationContext={"groups"={"vacancies:write"}}
 * )

 */
class Vacancies
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"vacancies:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $department;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $level;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $closing_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $publish_date;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $salary;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $create_at;

    /**
     * @ORM\OneToMany(targetEntity=VacancyRequirements::class, mappedBy="vacancy")
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $vacancyRequirements;

    /**
     * @ORM\OneToMany(targetEntity=VacancyResponsabilities::class, mappedBy="vacancy")
     * @Groups({"vacancies:read", "vacancies:write"})
     */
    private $vacancyResponsabilities;

    public function __construct()
    {
        $this->vacancyRequirements = new ArrayCollection();
        $this->vacancyResponsabilities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(?string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(?string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closing_date;
    }

    public function setClosingDate(?\DateTimeInterface $closing_date): self
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(?\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(?string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection<int, VacancyRequirements>
     */
    public function getVacancyRequirements(): Collection
    {
        return $this->vacancyRequirements;
    }

    public function addVacancyRequirement(VacancyRequirements $vacancyRequirement): self
    {
        if (!$this->vacancyRequirements->contains($vacancyRequirement)) {
            $this->vacancyRequirements[] = $vacancyRequirement;
            $vacancyRequirement->setVacancy($this);
        }

        return $this;
    }

    public function removeVacancyRequirement(VacancyRequirements $vacancyRequirement): self
    {
        if ($this->vacancyRequirements->removeElement($vacancyRequirement)) {
            // set the owning side to null (unless already changed)
            if ($vacancyRequirement->getVacancy() === $this) {
                $vacancyRequirement->setVacancy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VacancyResponsabilities>
     */
    public function getVacancyResponsabilities(): Collection
    {
        return $this->vacancyResponsabilities;
    }

    public function addVacancyResponsability(VacancyResponsabilities $vacancyResponsability): self
    {
        if (!$this->vacancyResponsabilities->contains($vacancyResponsability)) {
            $this->vacancyResponsabilities[] = $vacancyResponsability;
            $vacancyResponsability->setVacancy($this);
        }

        return $this;
    }

    public function removeVacancyResponsability(VacancyResponsabilities $vacancyResponsability): self
    {
        if ($this->vacancyResponsabilities->removeElement($vacancyResponsability)) {
            // set the owning side to null (unless already changed)
            if ($vacancyResponsability->getVacancy() === $this) {
                $vacancyResponsability->setVacancy(null);
            }
        }

        return $this;
    }
}

website-backend/src/Form/VacanciesType.php
<?php

namespace App\Form;

use App\Entity\Vacancies;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VacanciesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('department')
            ->add('location')
            ->add('type')
            ->add('level')
            ->add('closing_date')
            ->add('publish_date')
            ->add('salary')
            ->add('create_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vacancies::class,
        ]);
    }
}

website-backend/src/Controller/VacanciesController.php
<?php

namespace App\Controller;

use App\Entity\Vacancies;
use App\Form\Vacancies1Type;
use App\Repository\VacanciesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/vacancies")
 */
class VacanciesController extends AbstractController
{
    /**
     * @Route("/", name="app_vacancies_index", methods={"GET"})
     */
    public function index(VacanciesRepository $vacanciesRepository): Response
    {
        return $this->render('vacancies/index.html.twig', [
            'vacancies' => $vacanciesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_vacancies_new", methods={"GET", "POST"})
     */
    public function new(Request $request, VacanciesRepository $vacanciesRepository): Response
    {
        $vacancy = new Vacancies();
        $form = $this->createForm(Vacancies1Type::class, $vacancy);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vacanciesRepository->add($vacancy, true);

            return $this->redirectToRoute('app_vacancies_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vacancies/new.html.twig', [
            'vacancy' => $vacancy,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_vacancies_show", methods={"GET"})
     */
    public function show(Vacancies $vacancy): Response
    {
        return $this->render('vacancies/show.html.twig', [
            'vacancy' => $vacancy,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_vacancies_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Vacancies $vacancy, VacanciesRepository $vacanciesRepository): Response
    {
        $form = $this->createForm(Vacancies1Type::class, $vacancy);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vacanciesRepository->add($vacancy, true);

            return $this->redirectToRoute('app_vacancies_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vacancies/edit.html.twig', [
            'vacancy' => $vacancy,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_vacancies_delete", methods={"POST"})
     */
    public function delete(Request $request, Vacancies $vacancy, VacanciesRepository $vacanciesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vacancy->getId(), $request->request->get('_token'))) {
            $vacanciesRepository->remove($vacancy, true);
        }

        return $this->redirectToRoute('app_vacancies_index', [], Response::HTTP_SEE_OTHER);
    }
}

website-backend/templates/vacancies/_delete_form.html.twig
<form method="post" action="{{ path('app_vacancies_delete', {'id': vacancy.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vacancy.id) }}">
    <button class="btn">Delete</button>
</form>

website-backend/templates/vacancies/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

website-backend/templates/vacancies/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vacancies{% endblock %}

{% block body %}
    <h1>Edit Vacancies</h1>

    {{ include('vacancies/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vacancies_index') }}">back to list</a>

    {{ include('vacancies/_delete_form.html.twig') }}
{% endblock %}

website-backend/templates/vacancies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vacancies index{% endblock %}

{% block body %}
    <h1>Vacancies index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Department</th>
                <th>Location</th>
                <th>Type</th>
                <th>Level</th>
                <th>Closing_date</th>
                <th>Publish_date</th>
                <th>Salary</th>
                <th>Create_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vacancy in vacancies %}
            <tr>
                <td>{{ vacancy.id }}</td>
                <td>{{ vacancy.title }}</td>
                <td>{{ vacancy.department }}</td>
                <td>{{ vacancy.location }}</td>
                <td>{{ vacancy.type }}</td>
                <td>{{ vacancy.level }}</td>
                <td>{{ vacancy.closingDate ? vacancy.closingDate|date('Y-m-d') : '' }}</td>
                <td>{{ vacancy.publishDate ? vacancy.publishDate|date('Y-m-d') : '' }}</td>
                <td>{{ vacancy.salary }}</td>
                <td>{{ vacancy.createAt ? vacancy.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_vacancies_show', {'id': vacancy.id}) }}">show</a>
                    <a href="{{ path('app_vacancies_edit', {'id': vacancy.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_vacancies_new') }}">Create new</a>
{% endblock %}

website-backend/templates/vacancies/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vacancies{% endblock %}

{% block body %}
    <h1>Create new Vacancies</h1>

    {{ include('vacancies/_form.html.twig') }}

    <a href="{{ path('app_vacancies_index') }}">back to list</a>
{% endblock %}

website-backend/templates/vacancies/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vacancies{% endblock %}

{% block body %}
    <h1>Vacancies</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vacancy.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ vacancy.title }}</td>
            </tr>
            <tr>
                <th>Department</th>
                <td>{{ vacancy.department }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ vacancy.location }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ vacancy.type }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ vacancy.level }}</td>
            </tr>
            <tr>
                <th>Closing_date</th>
                <td>{{ vacancy.closingDate ? vacancy.closingDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Publish_date</th>
                <td>{{ vacancy.publishDate ? vacancy.publishDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>{{ vacancy.salary }}</td>
            </tr>
            <tr>
                <th>Create_at</th>
                <td>{{ vacancy.createAt ? vacancy.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vacancies_index') }}">back to list</a>

    <a href="{{ path('app_vacancies_edit', {'id': vacancy.id}) }}">edit</a>

    {{ include('vacancies/_delete_form.html.twig') }}
{% endblock %}